# Generated by Django 5.1.5 on 2025-01-16 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название стеллажа')),
                ('capacity', models.PositiveIntegerField(verbose_name='Вместимость стелажа')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Расположение')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('publisher', models.CharField(max_length=255, verbose_name='Издательство')),
                ('publication_year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('genre', models.CharField(max_length=100, verbose_name='Жанр')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('shelf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='bookstore.shelf', verbose_name='Стеллаж')),
            ],
        ),
    ]
