# Generated by Django 5.1.5 on 2025-01-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelf',
            name='location',
        ),
        migrations.AddField(
            model_name='shelf',
            name='current_occupation',
            field=models.IntegerField(default=0),
        ),
    ]
